From 67ab4d304639d6f0bb24e6ff30b2aa4bc05fbc19 Mon Sep 17 00:00:00 2001
From: Yaroslav Halchenko <debian@onerussian.com>
Date: Fri, 17 Sep 2021 15:48:27 -0400
Subject: [PATCH] Skip 2 tests which now fail on conda

---
 datalad/customremotes/tests/test_archives.py | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/datalad/customremotes/tests/test_archives.py b/datalad/customremotes/tests/test_archives.py
index c633d5723..ebf1507c2 100644
--- a/datalad/customremotes/tests/test_archives.py
+++ b/datalad/customremotes/tests/test_archives.py
@@ -38,6 +38,7 @@ from ...tests.utils import (
     chpwd,
     eq_,
     in_,
+    known_failure,
     known_failure_githubci_win,
     ok_,
     serve_path_via_http,
@@ -70,7 +71,7 @@ from datalad import cfg as dl_cfg
 
 # TODO: with_tree ATM for archives creates this nested top directory
 # matching archive name, so it will be a/d/test.dat ... we don't want that probably
-@known_failure_githubci_win
+@known_failure  # conda
 @with_tree(
     tree=(('a.tar.gz', {'d': {fn_in_archive_obscure: '123'}}),
           ('simple.txt', '123'),
@@ -152,7 +153,7 @@ def test_basic_scenario(d, d2):
     # verify that we can't drop a file if archive key was dropped and online archive was removed or changed size! ;)
 
 
-@known_failure_githubci_win
+@known_failure  # conda
 @with_tree(
     tree={'a.tar.gz': {'d': {fn_in_archive_obscure: '123'}}}
 )
-- 
2.33.0

